# Generated by Django 5.2.6 on 2025-11-06 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('engineering', 'Engineering'), ('environmental_science', 'Environmental Science'), ('history', 'History'), ('literature', 'Literature'), ('philosophy', 'Philosophy'), ('languages', 'Languages'), ('music', 'Music'), ('fine_arts', 'Fine Arts'), ('cultural_studies', 'Cultural Studies'), ('psychology', 'Psychology'), ('sociology', 'Sociology'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('anthropology', 'Anthropology'), ('geography', 'Geography'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('management', 'Management'), ('business_administration', 'Business Administration'), ('law', 'Law'), ('international_relations', 'International Relations'), ('medicine', 'Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('public_health', 'Public Health'), ('physiotherapy', 'Physiotherapy'), ('education', 'Education'), ('media_communication', 'Media & Communication'), ('architecture', 'Architecture'), ('design', 'Design'), ('theology', 'Theology / Religious Studies')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='post_documents/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('misleading', 'Incorrect / Misleading Content'), ('spam', 'Spam / Irrelevant Files')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
            ],
        ),
    ]
